Improve js tlf
Adalab/f-m2-group4 pull request #3
Opened 2019-04-11 10:19 UTC by daniela932910

i changed the following files:

_-modified: _src/templates/partials/_fillApp.html_ 
           -   `line32` in the email`s placeholder, i just added a **d**(previous it was don´t be scare, now it´s correctly spelled - don´t be scare**d**)
           - in the `line 37` in the phone´s placeholder, i removed the **-** and changed the max-length to 9 characters
	
_- modified:   _src/assets/scss/layout/_panelFillApp.scss_ 
             -  in `line 58` i added a class `addBoxShadow__IfInputIsFIlled ` for the box shadow properties

In the files bellow : 

	modified:   _src/assets/js/fill-tlf.js
             - o changed the function `addBoxshadowifFilled` which adds the border shadow, giving it, two parameters, `inputEL,previewIcon`

-in each of the below files:
     - i picked-up the box(list element) of each icon.
     - called the function `addBoxshadowifFilled` in each file and gave it the parameters of the input.value of each element and the preview icon-the box(list element that i picked up);

	modified:   _src/assets/js/fill-github.js
	modified:   _src/assets/js/fill-linkedin.js
        modified:   _src/assets/js/fill-email.js
	
Could you please take a look and let me know if it's ok to merge with dev?

Thank you.

2019-04-12 18:18 UTC, carmen-tm requested changes
Great job, Ioana, I love this implementation! I have just a small visual remark... I feel that colour green with opacity=1 looks too strong... I would try to improve it visually. I see 2 possibilities for you to try:

1. "Listen", the colour choice of the user, and paint the shawdow like that, very light >> following Eva's code on `Improve js bgc` branch.
2. Or use a simple grey neutral color for all, (for example `color-neutral-400`).

The second one might be easier, but feel free to try whatever you want! It's super cool :)

2019-04-14 15:59 UTC, daniela932910 commented
Hi, i changed the color of the box shadow to grey, and also i am not able to add the variable you mentioned, it doesn't work because it's a property of the box-shadow:

```
.addBoxShadow__IfInputIsFIlled{
    box-shadow: 0px 0px 14px 2px grey;
```

Let me know if it seems ok to you and if i can merge with dev. Thank you

2019-04-14 16:13 UTC, carmen-tm approved these changes

2019-04-14 16:17 UTC, carmen-tm commented
Hi Ioana! Cool, a netural grey looks great as well, let's go for it!
I just have a comment on it... I think is better if we stick to our sass 'colour variables' palette created in our core folder when picking a colour... in this case, I would go for something lighter than the grey picked now, something a bit more subtle. What about the `color-neutral-400` ? Youlike it?

2019-04-15 18:44 UTC, merged